In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("D:\Downloads\wine+quality\winequality-red.csv", sep=";")

In [7]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
train, test = train_test_split(df)

In [10]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1006,9.1,0.29,0.33,2.05,0.063,13.0,27.0,0.99516,3.26,0.84,11.7,7
734,7.7,0.56,0.20,2.00,0.075,9.0,39.0,0.99870,3.48,0.62,9.3,5
213,8.2,0.57,0.26,2.20,0.060,28.0,65.0,0.99590,3.30,0.43,10.1,5
1473,6.1,0.60,0.08,1.80,0.071,14.0,45.0,0.99336,3.38,0.54,11.0,5
455,11.3,0.62,0.67,5.20,0.086,6.0,19.0,0.99880,3.22,0.69,13.4,8
...,...,...,...,...,...,...,...,...,...,...,...,...
1118,7.1,0.39,0.12,2.10,0.065,14.0,24.0,0.99252,3.30,0.53,13.3,6
571,6.2,0.36,0.24,2.20,0.095,19.0,42.0,0.99460,3.57,0.57,11.7,6
468,11.4,0.36,0.69,2.10,0.090,6.0,21.0,1.00000,3.17,0.62,9.2,6
942,10.1,0.43,0.40,2.60,0.092,13.0,52.0,0.99834,3.22,0.64,10.0,7
1182,10.2,0.40,0.40,2.50,0.068,41.0,54.0,0.99754,3.38,0.86,10.5,6

In [11]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1266,7.2,0.570,0.05,2.3,0.081,16.0,36.0,0.99564,3.38,0.60,10.3,6
52,6.6,0.500,0.04,2.1,0.068,6.0,14.0,0.99550,3.39,0.64,9.4,6
913,9.4,0.395,0.46,4.6,0.094,3.0,10.0,0.99639,3.27,0.64,12.2,7
1523,6.8,0.480,0.25,2.0,0.076,29.0,61.0,0.99530,3.34,0.60,10.4,5
1551,7.1,0.670,0.00,2.3,0.083,18.0,27.0,0.99768,3.44,0.54,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
852,8.0,0.420,0.32,2.5,0.080,26.0,122.0,0.99801,3.22,1.07,9.7,5
388,7.8,0.460,0.26,1.9,0.088,23.0,53.0,0.99810,3.43,0.74,9.2,6
1424,8.3,0.260,0.37,1.4,0.076,8.0,23.0,0.99740,3.26,0.70,9.6,6
679,10.8,0.260,0.45,3.3,0.060,20.0,49.0,0.99720,3.13,0.54,9.6,5
278,10.3,0.320,0.45,6.4,0.073,5.0,13.0,0.99760,3.23,0.82,12.6,8